

        <?php

/**
 * Unified Block Registry — single source of truth for all page blocks.
 *
 * Replaces both page_builder.php (sections) and content_blocks.php (content blocks).
 *
 * Block Categories:
 *   • data          — Dynamic blocks that pull from database (services, testimonials, etc.)
 *   • content       — Static content blocks (heading, paragraph, rich text, etc.)
 *   • layout        — Structural blocks (columns, tabs, accordions, etc.)
 *   • media         — Visual blocks (image, video, gallery, slider, etc.)
 *   • interactive   — Engagement blocks (CTA, form, map, counter, etc.)
 *
 * Each block type defines:
 *   - label, icon, category
 *   - content_fields: static content fields
 *   - data_source: dynamic data configuration (for data blocks)
 *   - style_fields: styling options
 *   - defaults
 */

return [

    'section_map' => [
        'hero' => 'hero',
        'stats_bar' => 'stats_bar',
        'services_grid' => 'services_grid',
        'local_about' => 'local_about',
        'process_steps' => 'process_steps',
        'portfolio_gallery' => 'portfolio_gallery',
        'testimonials' => 'testimonials',
        'faq_section' => 'faq_section',
        'trust_badges' => 'trust_badges',
        'cta_section' => 'cta_section',
        'city_grid' => 'city_grid',
        'blog_strip' => 'blog_strip',
        'service_hero' => 'hero',
        'scp_hero' => 'hero',
        'service_body' => 'rich_text',
        'local_intro' => 'rich_text',
        'benefits_grid' => 'stats_bar',
        'portfolio_preview' => 'portfolio_gallery',
        'city_availability' => 'city_availability',
        'marquee_strip' => 'marquee_strip',
        'parallax_media_band' => 'parallax_media_band',
        'authority_grid' => 'authority_grid',
        'service_area_enclave' => 'service_area_enclave',
        'split_consultation_panel' => 'split_consultation_panel',
    ],

    'strict_unified_page_types' => [
        'home',
        'services_hub',
        'service_category',
        'service',
        'locations_hub',
        'city',
        'theme_layout',
        'template_card',
    ],

    /*
    |--------------------------------------------------------------------------
    | Universal Style Fields (applies to every block)
    |--------------------------------------------------------------------------
    */
    'style_fields' => [
        // Background
        [
            'key' => 'surface_preset',
            'label' => 'Surface Preset',
            'type' => 'select',
            'tab' => 'background',
            'options' => [
                'none' => 'Default',
                'white' => 'White',
                'airy-gradient' => 'Airy Gradient',
                'deep-green' => 'Deep Green',
                'muted-light-green' => 'Muted Light Green',
                'image-dark-overlay' => 'Image-Backed Dark Overlay',
                'dark-strip' => 'Dark Strip',
                'premium-neutral' => 'Premium Neutral',
            ],
        ],
        [
            'key' => 'bg_color',
            'label' => 'Background Color',
            'type' => 'select',
            'tab' => 'background',
            'options' => [
                'none' => 'Transparent',
                'white' => 'White',
                'cream' => 'Cream',
                'gray' => 'Light Gray',
                'forest' => 'Forest Green',
                'dark' => 'Dark',
            ],
        ],
        ['key' => 'bg_image_id', 'label' => 'Background Image', 'type' => 'media', 'tab' => 'background'],
        [
            'key' => 'overlay_preset',
            'label' => 'Overlay Preset',
            'type' => 'select',
            'tab' => 'background',
            'options' => [
                'none' => 'None',
                'light' => 'Light (Glass)',
                'dark' => 'Dark',
                'forest' => 'Forest Tint',
            ],
        ],
        [
            'key' => 'bg_overlay_opacity',
            'label' => 'Overlay Opacity',
            'type' => 'range',
            'tab' => 'background',
            'min' => 0,
            'max' => 100,
            'step' => 5,
            'default' => 50,
        ],
        [
            'key' => 'surface_style',
            'label' => 'Legacy Surface Style',
            'type' => 'select',
            'tab' => 'background',
            'options' => [
                'none' => 'Default',
                'sage-gradient' => 'Sage Gradient',
                'forest-gradient' => 'Forest Gradient',
                'cream-panel' => 'Cream Panel',
                'glass-light' => 'Glass Light',
                'glass-dark' => 'Glass Dark',
                'stone-wash' => 'Stone Wash',
            ],
        ],
        [
            'key' => 'glass_effect',
            'label' => 'Glass Effect',
            'type' => 'select',
            'tab' => 'background',
            'options' => ['none' => 'None', 'subtle' => 'Subtle', 'strong' => 'Strong'],
        ],

        // Transitions
        [
            'key' => 'transition_top',
            'label' => 'Transition Top',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => [
                'none' => 'None',
                'fade-to-white' => 'Fade to White',
                'fade-from-white' => 'Fade from White',
                'fade-to-airy' => 'Fade to Airy',
                'fade-from-airy' => 'Fade from Airy',
                'dark-blend' => 'Dark Blend',
            ],
        ],
        [
            'key' => 'transition_bottom',
            'label' => 'Transition Bottom',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => [
                'none' => 'None',
                'fade-to-white' => 'Fade to White',
                'fade-from-white' => 'Fade from White',
                'fade-to-airy' => 'Fade to Airy',
                'fade-from-airy' => 'Fade from Airy',
                'dark-blend' => 'Dark Blend',
            ],
        ],

        // Spacing
        [
            'key' => 'spacing_preset',
            'label' => 'Spacing Preset',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'compact' => 'Compact', 'section' => 'Section', 'feature' => 'Feature', 'hero' => 'Hero'],
        ],
        [
            'key' => 'padding_top',
            'label' => 'Padding Top',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large', 'xl' => 'Extra Large'],
        ],
        [
            'key' => 'padding_bottom',
            'label' => 'Padding Bottom',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large', 'xl' => 'Extra Large'],
        ],
        [
            'key' => 'padding_left',
            'label' => 'Padding Left',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large'],
        ],
        [
            'key' => 'padding_right',
            'label' => 'Padding Right',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large'],
        ],
        [
            'key' => 'margin_top',
            'label' => 'Margin Top',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large', 'xl' => 'Extra Large'],
        ],
        [
            'key' => 'margin_bottom',
            'label' => 'Margin Bottom',
            'type' => 'select',
            'tab' => 'spacing',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large', 'xl' => 'Extra Large'],
        ],

        // Layout
        [
            'key' => 'content_width',
            'label' => 'Content Width Preset',
            'type' => 'select',
            'tab' => 'layout',
            'options' => [
                'default' => 'Default (Container)',
                'full' => 'Full Width',
                '7xl' => 'Wide (1280px)',
                '5xl' => 'Standard (1024px)',
                '3xl' => 'Narrow (768px)',
                'premium-narrow' => 'Editorial Narrow',
            ],
        ],
        [
            'key' => 'max_width',
            'label' => 'Legacy Max Width',
            'type' => 'select',
            'tab' => 'layout',
            'options' => ['full' => 'Full Width', 'xl' => '7xl (1280px)', 'lg' => '5xl (1024px)', 'md' => '3xl (768px)', 'sm' => 'xl (576px)'],
        ],
        [
            'key' => 'section_density_preset',
            'label' => 'Section Density',
            'type' => 'select',
            'tab' => 'layout',
            'options' => [
                'default' => 'Default',
                'compact' => 'Compact',
                'airy' => 'Airy (Luxury)',
            ],
        ],
        [
            'key' => 'text_color',
            'label' => 'Text Color',
            'type' => 'select',
            'tab' => 'layout',
            'options' => ['default' => 'Default', 'white' => 'White', 'dark' => 'Dark', 'forest' => 'Forest Green'],
        ],
        [
            'key' => 'text_align_preset',
            'label' => 'Text Alignment Preset',
            'type' => 'select',
            'tab' => 'layout',
            'options' => ['left' => 'Left', 'center' => 'Center', 'right' => 'Right'],
        ],
        [
            'key' => 'text_align',
            'label' => 'Legacy Text Align',
            'type' => 'select',
            'tab' => 'layout',
            'options' => ['left' => 'Left', 'center' => 'Center', 'right' => 'Right'],
        ],

        // Appearance
        [
            'key' => 'card_skin_preset',
            'label' => 'Card Skin Preset',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => [
                'default' => 'Default',
                'white-border' => 'White Bordered',
                'soft-elevated' => 'Soft Elevated',
                'quiet-hover' => 'Quiet Hover',
                'dark-panel' => 'Dark Panel',
            ],
        ],
        [
            'key' => 'border_style_preset',
            'label' => 'Border Style Preset',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => [
                'none' => 'None',
                'subtle' => 'Subtle (Light)',
                'gold' => 'Gold Accent',
                'dark' => 'Dark Edge',
            ],
        ],
        [
            'key' => 'shadow_elevation_preset',
            'label' => 'Shadow Elevation Preset',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => [
                'none' => 'None',
                'sm' => 'Small (Subtle)',
                'md' => 'Medium (Editorial)',
                'lg' => 'Large (Luxury)',
            ],
        ],
        [
            'key' => 'section_shell',
            'label' => 'Section Shell',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => ['none' => 'None', 'inset-panel' => 'Inset Panel', 'luxury-panel' => 'Luxury Panel', 'soft-panel' => 'Soft Panel'],
        ],
        [
            'key' => 'divider_style',
            'label' => 'Divider Style',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => [
                'none' => 'None',
                'top' => 'Top Border',
                'bottom' => 'Bottom Border',
                'both' => 'Top + Bottom',
                'gold-top' => 'Gold Top',
                'gold-bottom' => 'Gold Bottom',
            ],
        ],
        ['key' => 'rounded', 'label' => 'Rounded Corners', 'type' => 'toggle', 'tab' => 'appearance'],
        [
            'key' => 'border',
            'label' => 'Legacy Border',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => ['none' => 'None', 'light' => 'Light', 'medium' => 'Medium'],
        ],
        [
            'key' => 'shadow',
            'label' => 'Legacy Shadow',
            'type' => 'select',
            'tab' => 'appearance',
            'options' => ['none' => 'None', 'sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large'],
        ],
        ['key' => 'custom_class', 'label' => 'Custom CSS Class', 'type' => 'text', 'tab' => 'appearance'],

        // Advanced (Typography & Layering)
        [
            'key' => 'heading_scale_preset',
            'label' => 'Heading Scale Preset',
            'type' => 'select',
            'tab' => 'typography',
            'options' => [
                'default' => 'Default',
                'display' => 'Display (Hero)',
                'h1' => 'H1 (Primary)',
                'h2' => 'H2 (Section)',
                'h3' => 'H3 (Subsection)',
            ],
        ],
        [
            'key' => 'font_size',
            'label' => 'Global Font Size',
            'type' => 'select',
            'tab' => 'typography',
            'options' => ['default' => 'Default', 'sm' => 'Small', 'lg' => 'Large', 'xl' => 'Extra Large'],
        ],
        [
            'key' => 'font_weight',
            'label' => 'Global Font Weight',
            'type' => 'select',
            'tab' => 'typography',
            'options' => ['normal' => 'Normal', 'medium' => 'Medium', 'semibold' => 'Semibold', 'bold' => 'Bold'],
        ],
        ['key' => 'z_index', 'label' => 'Z-Index', 'type' => 'number', 'tab' => 'layout', 'default' => 0],
        [
            'key' => 'overflow',
            'label' => 'Overflow',
            'type' => 'select',
            'tab' => 'layout',
            'options' => ['visible' => 'Visible', 'hidden' => 'Hidden', 'clip' => 'Clip'],
        ],
    ],

    'style_defaults' => [
        'desktop' => [
            'surface_preset' => 'none',
            'bg_color' => 'none',
            'bg_image_id' => null,
            'overlay_preset' => 'none',
            'bg_overlay_opacity' => 50,
            'surface_style' => 'none',
            'glass_effect' => 'none',
            'transition_top' => 'none',
            'transition_bottom' => 'none',
            'spacing_preset' => 'section',
            'padding_top' => 'lg',
            'padding_bottom' => 'lg',
            'padding_left' => 'md',
            'padding_right' => 'md',
            'margin_top' => 'none',
            'margin_bottom' => 'lg',
            'content_width' => 'default',
            'max_width' => 'full',
            'section_density_preset' => 'default',
            'text_color' => 'default',
            'text_align_preset' => 'left',
            'text_align' => 'left',
            'card_skin_preset' => 'default',
            'border_style_preset' => 'none',
            'shadow_elevation_preset' => 'none',
            'section_shell' => 'none',
            'divider_style' => 'none',
            'rounded' => false,
            'border' => 'none',
            'shadow' => 'none',
            'custom_class' => '',
            'heading_scale_preset' => 'default',
        ],
        'tablet' => [],
        'mobile' => [],
    ],

    'theme_style_defaults' => [
        'desktop' => [
            'surface_preset' => 'none',
            'bg_color' => 'none',
            'bg_image_id' => null,
            'overlay_preset' => 'none',
            'bg_overlay_opacity' => 50,
            'surface_style' => 'none',
            'glass_effect' => 'none',
            'transition_top' => 'none',
            'transition_bottom' => 'none',
            'spacing_preset' => 'none',
            'padding_top' => 'none',
            'padding_bottom' => 'none',
            'padding_left' => 'none',
            'padding_right' => 'none',
            'margin_top' => 'none',
            'margin_bottom' => 'none',
            'content_width' => 'default',
            'max_width' => 'full',
            'section_density_preset' => 'default',
            'text_color' => 'default',
            'text_align_preset' => 'left',
            'text_align' => 'left',
            'card_skin_preset' => 'default',
            'border_style_preset' => 'none',
            'shadow_elevation_preset' => 'none',
            'section_shell' => 'none',
            'divider_style' => 'none',
            'rounded' => false,
            'border' => 'none',
            'shadow' => 'none',
            'custom_class' => '',
            'heading_scale_preset' => 'default',
        ],
        'tablet' => [],
        'mobile' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Block Type Registry
    |--------------------------------------------------------------------------
    */
    'types' => [

        // =====================================================================
        // DATA BLOCKS — Dynamic content from database
        // =====================================================================

        'hero' => [
            'label' => 'Hero Banner',
            'icon' => 'layout',
            'category' => 'data',
            'governance' => [
                'required_fields' => ['heading'],
                'variants' => [
                    'editorial' => [
                        'label' => 'Editorial',
                        'visible_fields' => ['heading', 'subtitle', 'eyebrow', 'cta_primary_text', 'cta_primary_url', 'cta_secondary_text', 'cta_secondary_url', 'hero_media_id', 'video_url', 'extra_image_ids', 'overlay_preset', 'overlay_opacity', 'align', 'height'],
                    ],
                ],
            ],
            'content_fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'subtitle', 'label' => 'Subtitle', 'type' => 'textarea'],
                ['key' => 'eyebrow', 'label' => 'Eyebrow/Tag', 'type' => 'text'],
                ['key' => 'cta_primary_text', 'label' => 'Primary CTA Text', 'type' => 'text'],
                ['key' => 'cta_primary_url', 'label' => 'Primary CTA URL', 'type' => 'text'],
                ['key' => 'cta_secondary_text', 'label' => 'Secondary CTA Text', 'type' => 'text'],
                ['key' => 'cta_secondary_url', 'label' => 'Secondary CTA URL', 'type' => 'text'],
                ['key' => 'hero_media_id', 'label' => 'Hero Image', 'type' => 'media'],
                ['key' => 'video_url', 'label' => 'Background Video URL', 'type' => 'text'],
                ['key' => 'extra_image_ids', 'label' => 'Additional Slider Images', 'type' => 'media_multi'],
                [
                    'key' => 'overlay_preset',
                    'label' => 'Overlay Preset',
                    'type' => 'select',
                    'options' => [
                        'gradient' => 'Gradient',
                        'solid' => 'Solid',
                        'none' => 'None',
                    ],
                ],
                ['key' => 'overlay_opacity', 'label' => 'Overlay Opacity', 'type' => 'text'],
                [
                    'key' => 'align',
                    'label' => 'Text Alignment',
                    'type' => 'select',
                    'options' => [
                        'center' => 'Center',
                        'left' => 'Left',
                    ],
                ],
                [
                    'key' => 'height',
                    'label' => 'Hero Height',
                    'type' => 'select',
                    'options' => [
                        'viewport' => 'Viewport',
                        'tall' => 'Tall',
                        'standard' => 'Standard',
                    ],
                ],
            ],
            'data_source' => null, // hero is content-driven
            'defaults' => [
                'heading' => '',
                'subtitle' => '',
                'eyebrow' => '',
                'cta_primary_text' => 'Book a Consultation',
                'cta_primary_url' => '/contact',
                'cta_secondary_text' => '',
                'cta_secondary_url' => '/portfolio',
                'hero_media_id' => null,
                'video_url' => '',
                'extra_image_ids' => [],
                'overlay_preset' => 'gradient',
                'overlay_opacity' => '50',
                'align' => 'center',
                'height' => 'viewport',
                'variant' => 'editorial',
            ],
        ],
        /*
        |--------------------------------------------------------------------------
        | Theme / Site Builder Blocks (FSE)
        |--------------------------------------------------------------------------
        */
        'site_logo' => [
            'label' => 'Site Logo',
            'icon' => 'image',
            'category' => 'theme',
            'content_fields' => [
                [
                    'key' => 'source',
                    'label' => 'Logo Source',
                    'type' => 'select',
                    'options' => [
                        'auto' => 'Auto',
                        'header_desktop' => 'Header Desktop Logo',
                        'header_mobile' => 'Header Mobile Logo',
                        'footer' => 'Footer Logo',
                    ],
                ],
                [
                    'key' => 'size',
                    'label' => 'Logo Size',
                    'type' => 'select',
                    'options' => ['sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large', 'xl' => 'Extra Large'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['auto' => 'Auto', 'light' => 'Light', 'dark' => 'Dark', 'muted' => 'Muted'],
                ],
                ['key' => 'show_tagline', 'label' => 'Show Tagline', 'type' => 'toggle'],
                ['key' => 'tagline', 'label' => 'Custom Tagline Override', 'type' => 'text'],
            ],
            'data_source' => null,
            'defaults' => [
                'source' => 'auto',
                'size' => 'lg',
                'tone' => 'auto',
                'show_tagline' => false,
                'tagline' => '',
            ],
        ],
        'theme_header_shell' => [
            'label' => 'Theme Header Shell',
            'icon' => 'panel-top',
            'category' => 'theme',
            'governance' => [
                'allowed_page_types' => ['theme_layout'],
                'supports_children_rules' => [
                    'slot_key' => '_layout_slot',
                    'allowed_slots' => ['left', 'center', 'right', 'mobile'],
                    'required_slots' => ['left', 'center', 'right'],
                ],
            ],
            'supports_children' => true,
            'content_fields' => [
                [
                    'key' => 'mode',
                    'label' => 'Header Surface',
                    'type' => 'select',
                    'options' => ['glass' => 'Glass', 'solid' => 'Solid', 'transparent' => 'Transparent'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark / White Text', 'light' => 'Light / Ink Text'],
                ],
                ['key' => 'sticky', 'label' => 'Sticky Header', 'type' => 'toggle'],
                ['key' => 'compact_on_scroll', 'label' => 'Compact on Scroll', 'type' => 'toggle'],
                ['key' => 'show_divider', 'label' => 'Show Bottom Divider', 'type' => 'toggle'],
                ['key' => 'show_shadow_on_scroll', 'label' => 'Show Shadow on Scroll', 'type' => 'toggle'],
                [
                    'key' => 'desktop_height',
                    'label' => 'Desktop Height',
                    'type' => 'select',
                    'options' => ['compact' => 'Compact', 'standard' => 'Standard', 'tall' => 'Tall'],
                ],
                [
                    'key' => 'scrolled_height',
                    'label' => 'Scrolled Height',
                    'type' => 'select',
                    'options' => ['tight' => 'Tight', 'compact' => 'Compact', 'standard' => 'Standard'],
                ],
                [
                    'key' => 'content_width',
                    'label' => 'Content Width',
                    'type' => 'select',
                    'options' => ['7xl' => '7xl', 'wide' => 'Wide', 'full' => 'Full Width'],
                ],
                [
                    'key' => 'mobile_overlay_style',
                    'label' => 'Mobile Overlay Style',
                    'type' => 'select',
                    'options' => ['fullscreen' => 'Fullscreen', 'sheet' => 'Sheet'],
                ],
                [
                    'key' => 'mobile_overlay_tone',
                    'label' => 'Mobile Overlay Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark', 'light' => 'Light'],
                ],
                ['key' => 'mobile_menu_label', 'label' => 'Mobile Menu Label', 'type' => 'text'],
            ],
            'data_source' => null,
            'defaults' => [
                'mode' => 'glass',
                'tone' => 'dark',
                'sticky' => true,
                'compact_on_scroll' => true,
                'show_divider' => true,
                'show_shadow_on_scroll' => true,
                'desktop_height' => 'standard',
                'scrolled_height' => 'compact',
                'content_width' => '7xl',
                'mobile_overlay_style' => 'fullscreen',
                'mobile_overlay_tone' => 'dark',
                'mobile_menu_label' => 'Menu',
            ],
        ],
        'navigation_menu' => [
            'label' => 'Navigation Menu',
            'icon' => 'menu',
            'category' => 'theme',
            'content_fields' => [
                [
                    'key' => 'layout',
                    'label' => 'Menu Layout',
                    'type' => 'select',
                    'options' => ['horizontal' => 'Horizontal', 'vertical' => 'Vertical', 'footer' => 'Footer Links', 'mobile_overlay' => 'Mobile Overlay'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark / White Text', 'light' => 'Light / Forest Text', 'muted' => 'Muted'],
                ],
                [
                    'key' => 'style',
                    'label' => 'Style',
                    'type' => 'select',
                    'options' => ['luxury' => 'Luxury', 'minimal' => 'Minimal'],
                ],
                ['key' => 'show_services', 'label' => 'Show Services', 'type' => 'toggle'],
                ['key' => 'show_locations', 'label' => 'Show Locations', 'type' => 'toggle'],
                ['key' => 'show_portfolio', 'label' => 'Show Portfolio', 'type' => 'toggle'],
                ['key' => 'show_about', 'label' => 'Show About', 'type' => 'toggle'],
                ['key' => 'show_contact', 'label' => 'Show Contact', 'type' => 'toggle'],
                ['key' => 'service_limit', 'label' => 'Services Limit', 'type' => 'number'],
                ['key' => 'city_limit', 'label' => 'Cities Limit', 'type' => 'number'],
            ],
            'data_source' => null,
            'defaults' => [
                'layout' => 'horizontal',
                'tone' => 'dark',
                'style' => 'luxury',
                'show_services' => true,
                'show_locations' => true,
                'show_portfolio' => true,
                'show_about' => true,
                'show_contact' => true,
                'service_limit' => 6,
                'city_limit' => 8,
            ],
        ],
        'post_content' => [
            'label' => 'Post Content',
            'icon' => 'file-text',
            'category' => 'theme',
            'content_fields' => [],
            'data_source' => null,
            'defaults' => [],
        ],
        'theme_meta_data' => [
            'label' => 'Theme Meta Data',
            'icon' => 'hash',
            'category' => 'theme',
            'content_fields' => [
                ['key' => 'meta_key', 'label' => 'Meta Key (e.g. phone, footer_copyright_text)', 'type' => 'text'],
                [
                    'key' => 'display',
                    'label' => 'Display',
                    'type' => 'select',
                    'options' => ['inline' => 'Inline', 'stacked' => 'Stacked', 'pill' => 'Pill', 'paragraph' => 'Paragraph'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['inherit' => 'Inherit', 'light' => 'Light', 'dark' => 'Dark', 'accent' => 'Accent'],
                ],
                [
                    'key' => 'icon',
                    'label' => 'Icon',
                    'type' => 'select',
                    'options' => ['auto' => 'Auto', 'none' => 'None', 'phone' => 'Phone', 'mail' => 'Email', 'map-pin' => 'Map Pin', 'star' => 'Star', 'clock' => 'Clock'],
                ],
                ['key' => 'prefix', 'label' => 'Label Prefix', 'type' => 'text'],
            ],
            'data_source' => null,
            'defaults' => [
                'meta_key' => 'phone',
                'display' => 'inline',
                'tone' => 'inherit',
                'icon' => 'auto',
                'prefix' => '',
            ],
        ],
        'theme_contact_strip' => [
            'label' => 'Theme Contact Strip',
            'icon' => 'phone-call',
            'category' => 'theme',
            'content_fields' => [
                [
                    'key' => 'variant',
                    'label' => 'Variant',
                    'type' => 'select',
                    'options' => ['compact' => 'Compact', 'chips' => 'Chips', 'stacked' => 'Stacked'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark', 'light' => 'Light', 'muted' => 'Muted'],
                ],
                ['key' => 'show_phone', 'label' => 'Show Phone', 'type' => 'toggle'],
                ['key' => 'show_email', 'label' => 'Show Email', 'type' => 'toggle'],
                ['key' => 'show_rating', 'label' => 'Show Google Rating', 'type' => 'toggle'],
                ['key' => 'show_hours', 'label' => 'Show Hours', 'type' => 'toggle'],
            ],
            'data_source' => null,
            'defaults' => [
                'variant' => 'compact',
                'tone' => 'dark',
                'show_phone' => true,
                'show_email' => false,
                'show_rating' => true,
                'show_hours' => false,
            ],
        ],
        'theme_cta_group' => [
            'label' => 'Theme CTA Group',
            'icon' => 'mouse-pointer-click',
            'category' => 'theme',
            'content_fields' => [
                [
                    'key' => 'align',
                    'label' => 'Alignment',
                    'type' => 'select',
                    'options' => ['left' => 'Left', 'center' => 'Center', 'right' => 'Right'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark', 'light' => 'Light'],
                ],
                ['key' => 'primary_text', 'label' => 'Primary Button Text', 'type' => 'text'],
                ['key' => 'primary_url', 'label' => 'Primary Button URL', 'type' => 'text'],
                [
                    'key' => 'primary_style',
                    'label' => 'Primary Button Style',
                    'type' => 'select',
                    'options' => ['primary' => 'Primary', 'white' => 'White', 'ghost' => 'Ghost'],
                ],
                ['key' => 'secondary_text', 'label' => 'Secondary Button Text', 'type' => 'text'],
                ['key' => 'secondary_url', 'label' => 'Secondary Button URL', 'type' => 'text'],
                [
                    'key' => 'secondary_style',
                    'label' => 'Secondary Button Style',
                    'type' => 'select',
                    'options' => ['ghost' => 'Ghost', 'primary' => 'Primary', 'white' => 'White'],
                ],
            ],
            'data_source' => null,
            'defaults' => [
                'align' => 'right',
                'tone' => 'dark',
                'primary_text' => 'Book a Consultation',
                'primary_url' => '/contact',
                'primary_style' => 'ghost',
                'secondary_text' => '',
                'secondary_url' => '',
                'secondary_style' => 'white',
            ],
        ],
        'theme_social_links' => [
            'label' => 'Theme Social Links',
            'icon' => 'share-2',
            'category' => 'theme',
            'content_fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                [
                    'key' => 'source',
                    'label' => 'Source',
                    'type' => 'select',
                    'options' => ['settings' => 'Use Site Settings', 'manual' => 'Manual Links'],
                ],
                [
                    'key' => 'align',
                    'label' => 'Alignment',
                    'type' => 'select',
                    'options' => ['left' => 'Left', 'center' => 'Center', 'right' => 'Right'],
                ],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark', 'light' => 'Light'],
                ],
                [
                    'key' => 'size',
                    'label' => 'Icon Size',
                    'type' => 'select',
                    'options' => ['sm' => 'Small', 'md' => 'Medium', 'lg' => 'Large'],
                ],
                [
                    'key' => 'links',
                    'label' => 'Manual Links',
                    'type' => 'repeater',
                    'sub_fields' => [
                        ['key' => 'platform', 'label' => 'Platform', 'type' => 'text'],
                        ['key' => 'url', 'label' => 'URL', 'type' => 'text'],
                    ],
                ],
            ],
            'data_source' => null,
            'defaults' => [
                'heading' => '',
                'source' => 'settings',
                'align' => 'left',
                'tone' => 'dark',
                'size' => 'md',
                'links' => [],
            ],
        ],
        'theme_newsletter_panel' => [
            'label' => 'Theme Newsletter Panel',
            'icon' => 'mail-plus',
            'category' => 'theme',
            'content_fields' => [
                ['key' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text'],
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark', 'cream' => 'Cream', 'light' => 'Light'],
                ],
                [
                    'key' => 'layout',
                    'label' => 'Layout',
                    'type' => 'select',
                    'options' => ['split' => 'Split', 'stacked' => 'Stacked'],
                ],
                ['key' => 'placeholder', 'label' => 'Input Placeholder', 'type' => 'text'],
                ['key' => 'button_text', 'label' => 'Button Text', 'type' => 'text'],
            ],
            'data_source' => null,
            'defaults' => [
                'eyebrow' => 'Stay Updated',
                'heading' => '',
                'description' => '',
                'tone' => 'dark',
                'layout' => 'split',
                'placeholder' => 'your@email.com',
                'button_text' => 'Subscribe',
            ],
        ],
        'theme_footer_columns' => [
            'label' => 'Theme Footer Columns',
            'icon' => 'columns-3',
            'category' => 'theme',
            'content_fields' => [
                [
                    'key' => 'source',
                    'label' => 'Columns Source',
                    'type' => 'select',
                    'options' => ['settings' => 'Footer Settings', 'auto' => 'Auto Generated'],
                ],
                ['key' => 'show_services', 'label' => 'Show Services Column', 'type' => 'toggle'],
                ['key' => 'show_locations', 'label' => 'Show Locations Column', 'type' => 'toggle'],
                ['key' => 'show_company', 'label' => 'Show Company Column', 'type' => 'toggle'],
                ['key' => 'services_heading', 'label' => 'Services Heading', 'type' => 'text'],
                ['key' => 'locations_heading', 'label' => 'Locations Heading', 'type' => 'text'],
                ['key' => 'company_heading', 'label' => 'Company Heading', 'type' => 'text'],
                ['key' => 'show_call_panel', 'label' => 'Show Call Panel', 'type' => 'toggle'],
            ],
            'data_source' => null,
            'defaults' => [
                'source' => 'settings',
                'show_services' => true,
                'show_locations' => true,
                'show_company' => true,
                'services_heading' => 'Services',
                'locations_heading' => 'Locations',
                'company_heading' => 'Company',
                'show_call_panel' => true,
            ],
        ],
        'theme_legal_bar' => [
            'label' => 'Theme Legal Bar',
            'icon' => 'scale',
            'category' => 'theme',
            'content_fields' => [
                [
                    'key' => 'tone',
                    'label' => 'Tone',
                    'type' => 'select',
                    'options' => ['dark' => 'Dark', 'light' => 'Light'],
                ],
                ['key' => 'show_copyright', 'label' => 'Show Copyright', 'type' => 'toggle'],
                [
                    'key' => 'links_source',
                    'label' => 'Links Source',
                    'type' => 'select',
                    'options' => ['settings' => 'Footer Settings', 'default' => 'Default Links', 'custom' => 'Custom Links'],
                ],
                ['key' => 'custom_links_text', 'label' => 'Custom Links (Label|URL per line)', 'type' => 'textarea'],
            ],
            'data_source' => null,
            'defaults' => [
                'tone' => 'dark',
                'show_copyright' => true,
                'links_source' => 'settings',
                'custom_links_text' => '',
            ],
        ],

        

